# use the setting below to set multiple docs directories.
# docSections = ["drivers"]

uniqueHomePage = true # change to false to add sidebar to homepage

#blogDir = "blog" # can be posts, blog e.t.c

repo = "https://github.com/josehelps/compose"

#time_format_blog = "Monday, January 02, 2006"
#time_format_default = "January 2, 2006"
enableDarkMode = true # set to false to disable darkmode by default # user will still have the option to use dark mode

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 7

# show/hide line numbers by default. Switch to `true` if you'd rather have them on.
showLineNumbers = false

# By default the template will look for icons under the icons directory. In some situations you might wanna change that. edit the line below
# iconsPath = 'icons/'

otherSearchableFields = ["Tags"] # As they appear in frontmatter
[search]
  on = false
  global = false


# Site logo
[logo]
  #lightMode = "images/compose.svg"
  #darkMode = "images/compose-light.svg"
  lightMode = "images/logo.png"
  darkMode = "images/logo-dark.png"


[source]
  name = "GitHub"
  iconLight = "images/GitHubMarkLight.svg"
  iconDark = "images/GitHubMarkDark.svg"
  url = "https://github.com/magicsword-io/LOLDrivers"

[author]  
  name = "With ♥️ from Magicsword"
  url = "https://loldrivers.io/about"

