# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate Site

on: 
  push:
    branches: [ main ]

jobs:
  generate-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11
    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
    - name: Install dependencies with Poetry
      run: poetry install
    - name: Run Site Generation 
      run: poetry run python bin/site.py
    - name: Run Site Generation 
      run: poetry run python bin/gen-files.py
    - name: Commit Generated Data
      run: |
          git config --global user.name "Github Actions"
          git config --global user.email "robot@noreply.github.com"
          git config --global push.default simple
          git add .
          git commit -m "New site and hashes generated by GitHub Actions [ci skip]"
          git push
